name: Test Pygame

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      "CI": "true"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        echo "Lint run"
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
